#pragma once

#ifndef MISCOUNT_ERRORS
#define MISCOUNT_ERRORS

#define EXIT_NO_ARGS 				1
#define EXIT_MEM_ERROR 				2
#define EXIT_PROBABLY_NO_HOME 		3
#define EXIT_CANT_RETRIEVE			4
#define EXIT_FILEIO_FAIL			5
#define EXIT_CMD_BUILD_FAILED		6
#define EXIT_BUILT_CMD_TRUNCATED 	7

#endif // MISCOUNT_ERRORS